
package mypackage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "authorPortType", targetNamespace = "http://www.lqdev.cn/webservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthorPortType {


    /**
     * 
     * @param authorName
     * @return
     *     returns mypackage.AuthorDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorByName", targetNamespace = "http://www.lqdev.cn/webservice", className = "mypackage.GetAuthorByName")
    @ResponseWrapper(localName = "getAuthorByNameResponse", targetNamespace = "http://www.lqdev.cn/webservice", className = "mypackage.GetAuthorByNameResponse")
    public AuthorDto getAuthorByName(
        @WebParam(name = "authorName", targetNamespace = "")
        String authorName);

    /**
     * 
     * @return
     *     returns java.util.List<mypackage.AuthorDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorList", targetNamespace = "http://www.lqdev.cn/webservice", className = "mypackage.GetAuthorList")
    @ResponseWrapper(localName = "getAuthorListResponse", targetNamespace = "http://www.lqdev.cn/webservice", className = "mypackage.GetAuthorListResponse")
    public List<AuthorDto> getAuthorList();

    /**
     * 
     * @param authorName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorString", targetNamespace = "http://www.lqdev.cn/webservice", className = "mypackage.GetAuthorString")
    @ResponseWrapper(localName = "getAuthorStringResponse", targetNamespace = "http://www.lqdev.cn/webservice", className = "mypackage.GetAuthorStringResponse")
    public String getAuthorString(
        @WebParam(name = "authorName", targetNamespace = "")
        String authorName);

}
